# .github/dependabot.yml

version: 2
updates:
  - package-ecosystem: "npm" # or "maven", "pip", "gradle", etc., adjust as needed
    directory: "/"
    schedule:
      interval: "weekly" # can be "daily", "weekly", or "monthly"
      day: "sunday"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct" # only direct dependencies, no noisy transitive ones
    ignore:
      - dependency-name: "left-pad" # example of a package to ignore
        versions: ["*"]

    groups:
      security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
      regular-updates:
        applies-to: "version-updates"
        patterns:
          - "*"

# Optional: uncomment if you want to enable for another ecosystem too
#  - package-ecosystem: "github-actions"
#    directory: "/"
#    schedule:
#      interval: "weekly"
